"""
Build orchestrator.

Coordinates the full agentic pipeline: code generation → dependency install →
build → CI/Docker/deploy setup — all autonomous, no manual steps.
"""

from pathlib import Path
from typing import Optional, Callable

from anyplace.core.plan_generator import ProjectPlan
from anyplace.core.code_generator import CodeGenerator
from anyplace.core.git_manager import GitManager
from anyplace.core.llm_provider import LLMProvider
from anyplace.cli.error_handler import GenerationError, APIError
from anyplace.core.hooks_injector import HooksInjector
from anyplace.core.guide_generator import GuideGenerator
from anyplace.core.env_manager import EnvManager
from anyplace.core.doc_generator import DocGenerator


class BuildOrchestrator:
    """Orchestrates the entire build process — fully agentic, end-to-end."""

    def __init__(
        self,
        plan: ProjectPlan,
        llm_provider: Optional[LLMProvider] = None,
        project_dir: Optional[Path] = None,
        use_git: bool = True,
        agentic: bool = True,
        human_accept: bool = True,
    ):
        """
        Initialize build orchestrator.

        Args:
            plan: The ProjectPlan to build
            llm_provider: LLMProvider instance
            project_dir: Custom project directory
            use_git: Whether to initialize git repository
            agentic: If True, auto-install deps, build, and setup deployment
            human_accept: If True (default), ask user before each pipeline step
        """
        self.plan = plan
        self.llm_provider = llm_provider or LLMProvider()
        self.project_dir = project_dir
        self.use_git = use_git
        self.agentic = agentic
        self.human_accept = human_accept

        self.code_generator: Optional[CodeGenerator] = None
        self.git_manager: Optional[GitManager] = None
        self.pipeline_result = None  # Set after agentic pipeline runs

    def build(
        self,
        progress_callback: Optional[Callable[[str, int, int], None]] = None,
        agent_callback: Optional[Callable[[str, str], None]] = None,
    ) -> bool:
        """
        Execute the full build process.

        When agentic=True, this also installs deps, builds, and sets up
        CI/Docker/deploy — no manual steps needed.

        Args:
            progress_callback: Called with (current_file, index, total) during code gen
            agent_callback: Called with (step_name, status) during agentic pipeline

        Returns:
            True if successful

        Raises:
            GenerationError: If build fails
        """
        try:
            # Initialize generators
            self.code_generator = CodeGenerator(
                plan=self.plan,
                llm_provider=self.llm_provider,
                project_dir=self.project_dir,
            )

            self.git_manager = GitManager(self.code_generator.project_dir)

            # Check git availability if needed
            if self.use_git and not self.git_manager.check_git_installed():
                raise GenerationError(
                    "Git is not installed or not in PATH.\n"
                    "Install git from: https://git-scm.com/downloads\n"
                    "Or disable git with --no-git flag"
                )

            # Create project directory first (needed for git init)
            try:
                self.code_generator.project_dir.mkdir(parents=True, exist_ok=False)
            except FileExistsError:
                raise GenerationError(
                    f"Project directory already exists: {self.code_generator.project_dir}\n"
                    f"Choose a different project name or delete the existing directory."
                )

            # Initialize git repo
            if self.use_git:
                self.git_manager.init_repo()
                self.git_manager.create_gitignore()

            # Generate all files
            success = self.code_generator.generate_all(
                progress_callback=self._create_progress_callback(progress_callback),
            )

            if success and self.use_git:
                # Final commit
                self.git_manager.commit_bulk(
                    files=[f.path for f in self.plan.files],
                    message=f"Complete: {self.plan.project_name}\n\nGenerated by AnywhereCode",
                )

            if success:
                project_dir = self.code_generator.project_dir

                # Inject Claude Code integration (.claude/settings.json + commands)
                try:
                    injector = HooksInjector(project_dir)
                    injector.inject()
                except Exception:
                    pass

                # Generate learning guides (QUICKSTART.md + LEARNING.md)
                try:
                    guide_gen = GuideGenerator()
                    guide_gen.write_all(
                        template_name=self.plan.template,
                        project_name=self.plan.project_name,
                        tech_stack=self.plan.tech_stack,
                        next_steps=self.plan.next_steps,
                        project_dir=project_dir,
                    )
                except Exception:
                    pass

                # Generate .env.example if not already created by the plan
                try:
                    env_example = project_dir / ".env.example"
                    if not env_example.exists():
                        from anyplace.core.build_runner import BuildRunner
                        runner = BuildRunner(project_dir)
                        env_mgr = EnvManager()
                        env_mgr.write_env_example(
                            project_dir,
                            runner._detect_project_type(),
                            self.plan.project_name,
                        )
                except Exception:
                    pass

                # Generate CONTRIBUTING.md and CHANGELOG.md
                try:
                    doc_gen = DocGenerator(project_dir)
                    doc_gen.generate_all(
                        project_name=self.plan.project_name,
                        doc_type="contributing",
                    )
                    doc_gen.generate_all(
                        project_name=self.plan.project_name,
                        doc_type="changelog",
                    )
                except Exception:
                    pass

                # ── AGENTIC PIPELINE ─────────────────────────────────────
                # This is the key difference: instead of printing "next steps"
                # for the user to do manually, we DO THEM automatically.
                if self.agentic:
                    self.pipeline_result = self._run_agentic_pipeline(
                        project_dir, agent_callback
                    )

            return success

        except (GenerationError, APIError) as e:
            # Cleanup on failure
            if self.code_generator:
                self.code_generator.cleanup_on_failure()
            raise

    def _run_agentic_pipeline(
        self,
        project_dir: Path,
        callback: Optional[Callable[[str, str], None]] = None,
    ):
        """
        Run the full autonomous post-generation pipeline:
        install deps → build → env → CI → Docker → deploy → verify
        """
        from anyplace.core.agent_executor import AgentExecutor

        executor = AgentExecutor(
            project_dir=project_dir,
            progress_callback=callback,
            human_accept=self.human_accept,
        )

        return executor.run_full_pipeline()

    def _create_progress_callback(
        self,
        user_callback: Optional[Callable],
    ) -> Callable:
        """
        Create progress callback that handles git commits.

        Args:
            user_callback: User's progress callback

        Returns:
            Enhanced progress callback
        """
        def callback(file_path: str, index: int, total: int):
            # Call user callback
            if user_callback:
                user_callback(file_path, index, total)

            # Auto-commit if git enabled
            if self.use_git and self.git_manager:
                self.git_manager.add_and_commit(
                    file_path=file_path,
                    message=f"Add {file_path}",
                )

        return callback

    def get_project_info(self) -> dict:
        """Get information about the generated project."""
        if not self.code_generator:
            return {}

        return {
            "project_name": self.plan.project_name,
            "project_dir": str(self.code_generator.project_dir),
            "files_generated": len(self.code_generator.files_generated),
            "total_files": len(self.plan.files),
            "git_enabled": self.use_git and self.git_manager and self.git_manager.repo_initialized,
        }


if __name__ == "__main__":
    # Test orchestrator
    from anyplace.core.plan_generator import ProjectPlan, FileInfo
    import tempfile

    files = [
        FileInfo(
            path="README.md",
            description="Project readme",
            file_type="doc",
            dependencies=[],
        ),
    ]

    plan = ProjectPlan(
        project_name="test-build",
        template="backend-nodejs",
        description="Test build",
        tech_stack=["Node.js"],
        files=files,
        key_features=["Simple"],
        estimated_time="5 min",
        architecture_notes="Minimal",
        next_steps=["Start coding"],
    )

    with tempfile.TemporaryDirectory() as tmpdir:
        try:
            orchestrator = BuildOrchestrator(
                plan=plan,
                project_dir=Path(tmpdir) / "projects",
                use_git=False,  # Skip git for testing
            )

            print("✅ BuildOrchestrator initialized")
            print(f"   Project: {orchestrator.plan.project_name}")

        except Exception as e:
            print(f"❌ Error: {e}")
