"""
Build orchestrator.

Coordinates code generation, git management, and project setup.
"""

from pathlib import Path
from typing import Optional, Callable

from anyplace.core.plan_generator import ProjectPlan
from anyplace.core.code_generator import CodeGenerator
from anyplace.core.git_manager import GitManager
from anyplace.core.llm_provider import LLMProvider
from anyplace.cli.error_handler import GenerationError, APIError


class BuildOrchestrator:
    """Orchestrates the entire build process."""

    def __init__(
        self,
        plan: ProjectPlan,
        llm_provider: Optional[LLMProvider] = None,
        project_dir: Optional[Path] = None,
        use_git: bool = True,
    ):
        """
        Initialize build orchestrator.

        Args:
            plan: The ProjectPlan to build
            llm_provider: LLMProvider instance
            project_dir: Custom project directory
            use_git: Whether to initialize git repository
        """
        self.plan = plan
        self.llm_provider = llm_provider or LLMProvider()
        self.project_dir = project_dir
        self.use_git = use_git

        self.code_generator: Optional[CodeGenerator] = None
        self.git_manager: Optional[GitManager] = None

    def build(
        self,
        progress_callback: Optional[Callable[[str, int, int], None]] = None,
    ) -> bool:
        """
        Execute the full build process.

        Args:
            progress_callback: Called with (current_file, index, total)

        Returns:
            True if successful

        Raises:
            GenerationError: If build fails
        """
        try:
            # Initialize generators
            self.code_generator = CodeGenerator(
                plan=self.plan,
                llm_provider=self.llm_provider,
                project_dir=self.project_dir,
            )

            self.git_manager = GitManager(self.code_generator.project_dir)

            # Check git availability if needed
            if self.use_git and not self.git_manager.check_git_installed():
                raise GenerationError(
                    "Git is not installed or not in PATH.\n"
                    "Install git from: https://git-scm.com/downloads\n"
                    "Or disable git with --no-git flag"
                )

            # Create project directory first (needed for git init)
            try:
                self.code_generator.project_dir.mkdir(parents=True, exist_ok=False)
            except FileExistsError:
                raise GenerationError(
                    f"Project directory already exists: {self.code_generator.project_dir}\n"
                    f"Choose a different project name or delete the existing directory."
                )

            # Initialize git repo
            if self.use_git:
                self.git_manager.init_repo()
                self.git_manager.create_gitignore()

            # Generate all files
            success = self.code_generator.generate_all(
                progress_callback=self._create_progress_callback(progress_callback),
            )

            if success and self.use_git:
                # Final commit
                self.git_manager.commit_bulk(
                    files=[f.path for f in self.plan.files],
                    message=f"Complete: {self.plan.project_name}\n\nGenerated by AnywhereCode",
                )

            return success

        except (GenerationError, APIError) as e:
            # Cleanup on failure
            if self.code_generator:
                self.code_generator.cleanup_on_failure()
            raise

    def _create_progress_callback(
        self,
        user_callback: Optional[Callable],
    ) -> Callable:
        """
        Create progress callback that handles git commits.

        Args:
            user_callback: User's progress callback

        Returns:
            Enhanced progress callback
        """
        def callback(file_path: str, index: int, total: int):
            # Call user callback
            if user_callback:
                user_callback(file_path, index, total)

            # Auto-commit if git enabled
            if self.use_git and self.git_manager:
                self.git_manager.add_and_commit(
                    file_path=file_path,
                    message=f"Add {file_path}",
                )

        return callback

    def get_project_info(self) -> dict:
        """Get information about the generated project."""
        if not self.code_generator:
            return {}

        return {
            "project_name": self.plan.project_name,
            "project_dir": str(self.code_generator.project_dir),
            "files_generated": len(self.code_generator.files_generated),
            "total_files": len(self.plan.files),
            "git_enabled": self.use_git and self.git_manager and self.git_manager.repo_initialized,
        }


if __name__ == "__main__":
    # Test orchestrator
    from anyplace.core.plan_generator import ProjectPlan, FileInfo
    import tempfile

    files = [
        FileInfo(
            path="README.md",
            description="Project readme",
            file_type="doc",
            dependencies=[],
        ),
    ]

    plan = ProjectPlan(
        project_name="test-build",
        template="backend-nodejs",
        description="Test build",
        tech_stack=["Node.js"],
        files=files,
        key_features=["Simple"],
        estimated_time="5 min",
        architecture_notes="Minimal",
        next_steps=["Start coding"],
    )

    with tempfile.TemporaryDirectory() as tmpdir:
        try:
            orchestrator = BuildOrchestrator(
                plan=plan,
                project_dir=Path(tmpdir) / "projects",
                use_git=False,  # Skip git for testing
            )

            print("✅ BuildOrchestrator initialized")
            print(f"   Project: {orchestrator.plan.project_name}")

        except Exception as e:
            print(f"❌ Error: {e}")
