"""
Documentation generator.

Generates CONTRIBUTING.md, CHANGELOG.md, and API documentation
for generated projects.
"""

import re
from pathlib import Path
from typing import Dict, List, Optional

from anyplace.core.llm_provider import LLMProvider
from anyplace.core.build_runner import BuildRunner


class DocGenerator:
    """Generates project documentation files."""

    def __init__(self, project_dir: Path, llm_provider: Optional[LLMProvider] = None):
        self.project_dir = Path(project_dir)
        self.llm_provider = llm_provider
        self.runner = BuildRunner(self.project_dir)
        self.project_type = self.runner._detect_project_type()

    # ─────────────────────────────────────────────
    # CONTRIBUTING.md
    # ─────────────────────────────────────────────

    def generate_contributing_guide(self, project_name: str = "this project") -> str:
        """Generate CONTRIBUTING.md — hardcoded, no LLM needed."""
        return f"""# Contributing to {project_name}

Thank you for your interest in contributing! Here's how to get started.

---

## Getting Started

1. **Fork** the repository and **clone** your fork.
2. **Create a branch** for your feature or fix:
   ```bash
   git checkout -b feat/my-feature
   # or
   git checkout -b fix/my-bug
   ```
3. **Install dependencies** and make sure everything works:
   ```bash
   npm install
   npm run build
   ```
4. **Make your changes** — keep commits small and focused.
5. **Commit** with a clear message following [Conventional Commits](https://www.conventionalcommits.org/):
   ```
   feat(scope): add new feature
   fix(scope): fix specific bug
   docs: update README
   ```
6. **Push** your branch and open a **Pull Request**.

---

## Development Guidelines

### Code Style
- Follow the existing code style in the project.
- Run `npm run lint` before submitting — fix all lint errors.
- Write clear, self-documenting code; add comments only where logic is non-obvious.

### Testing
- Add tests for any new functionality.
- Make sure existing tests pass: `npm test`
- Aim for meaningful coverage, not just high numbers.

### Commit Messages
Use the [Conventional Commits](https://www.conventionalcommits.org/) spec:

| Prefix | Use for |
|--------|---------|
| `feat` | New feature |
| `fix` | Bug fix |
| `docs` | Documentation only |
| `chore` | Build, tooling, dependencies |
| `refactor` | Code restructure without behavior change |
| `test` | Adding or fixing tests |
| `style` | Formatting, whitespace |

---

## Pull Request Checklist

Before submitting a PR, make sure you have:

- [ ] Written or updated tests for the change
- [ ] Run `npm run lint` with no errors
- [ ] Run `npm test` with all tests passing
- [ ] Updated documentation if needed
- [ ] Written a clear PR description explaining _why_ the change is needed

---

## Reporting Bugs

Open an issue with:
- A clear, descriptive title
- Steps to reproduce
- Expected vs actual behavior
- Your environment (OS, Node version, etc.)

---

## Questions?

Open a Discussion or an Issue — we're happy to help!
"""

    # ─────────────────────────────────────────────
    # CHANGELOG.md
    # ─────────────────────────────────────────────

    def generate_changelog(
        self,
        project_name: str = "Project",
        version: str = "0.1.0",
    ) -> str:
        """Generate an initial CHANGELOG.md following Keep a Changelog format."""
        from datetime import date

        today = date.today().isoformat()

        return f"""# Changelog

All notable changes to **{project_name}** will be documented here.

Format follows [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
Versioning follows [Semantic Versioning](https://semver.org/).

---

## [Unreleased]

### Added
- _(Add future changes here)_

---

## [{version}] — {today}

### Added
- Initial project scaffold generated by [AnywhereCode](https://github.com/RudraO2/AnywhereCode)
- Project structure for {self.project_type} application
- Basic configuration files and development tooling
- `.env.example` with documented environment variables
- `QUICKSTART.md` and `LEARNING.md` for onboarding
- `.claude/` integration for Claude Code

[Unreleased]: https://github.com/user/repo/compare/v{version}...HEAD
[{version}]: https://github.com/user/repo/releases/tag/v{version}
"""

    # ─────────────────────────────────────────────
    # API Documentation
    # ─────────────────────────────────────────────

    def _collect_source_files(self) -> List[Path]:
        """Collect source files that may contain API endpoints or exports."""
        extensions = {".ts", ".tsx", ".js", ".jsx", ".py"}
        exclude_dirs = {"node_modules", "dist", "build", ".next", "__pycache__", ".venv"}

        files = []
        for path in self.project_dir.rglob("*"):
            if path.is_file() and path.suffix in extensions:
                if not any(part in exclude_dirs for part in path.parts):
                    files.append(path)

        return sorted(files)

    def _extract_exports(self, content: str) -> List[str]:
        """
        Extract exported function/class names from source code.

        Works for both TypeScript/JavaScript and Python exports.
        """
        exports = []

        # TypeScript/JavaScript: export function/class/const/default
        ts_pattern = re.compile(
            r"export\s+(?:default\s+)?(?:async\s+)?(?:function|class|const|let|var)\s+(\w+)",
            re.MULTILINE,
        )
        exports.extend(ts_pattern.findall(content))

        # Python: def/class at module level
        py_pattern = re.compile(r"^(?:def|class|async def)\s+(\w+)", re.MULTILINE)
        exports.extend(py_pattern.findall(content))

        return exports

    def generate_api_docs(self) -> str:
        """
        Generate API_DOCS.md by scanning source files and using LLM to document them.

        Falls back to a simple file listing if no LLM is configured.
        """
        source_files = self._collect_source_files()

        if not source_files:
            return "# API Documentation\n\n_No source files found._\n"

        if self.llm_provider:
            return self._generate_api_docs_with_llm(source_files)
        else:
            return self._generate_api_docs_basic(source_files)

    def _generate_api_docs_basic(self, source_files: List[Path]) -> str:
        """Generate simple file listing without LLM."""
        lines = [
            "# API Documentation",
            "",
            "> _Generated by AnywhereCode. Add descriptions manually or run_",
            "> _`anyplace docs --type api` with an LLM configured for richer docs._",
            "",
            "## Source Files",
            "",
        ]

        for path in source_files:
            rel = path.relative_to(self.project_dir)
            content = path.read_text(errors="ignore")
            exports = self._extract_exports(content)

            lines.append(f"### `{rel}`")
            if exports:
                lines.append("")
                lines.append("**Exports:**")
                for exp in exports[:10]:  # cap at 10 per file
                    lines.append(f"- `{exp}`")
            lines.append("")

        return "\n".join(lines)

    def _generate_api_docs_with_llm(self, source_files: List[Path]) -> str:
        """Use LLM to generate richer docs for each key source file."""
        lines = [
            "# API Documentation",
            "",
            f"> Generated by AnywhereCode · Project type: `{self.project_type}`",
            "",
        ]

        # Limit to 5 most interesting files to avoid huge token usage
        key_files = [
            f for f in source_files
            if any(kw in f.name for kw in ["route", "api", "index", "main", "app", "controller"])
        ][:5]

        if not key_files:
            key_files = source_files[:5]

        for path in key_files:
            rel = path.relative_to(self.project_dir)
            content = path.read_text(errors="ignore")

            if len(content) > 3000:
                content = content[:3000] + "\n... (truncated)"

            system = (
                "You are a technical writer. Given source code, write concise Markdown "
                "documentation describing what the file does and its key exports/endpoints. "
                "Use ## for the file heading, ### for subsections. Be brief."
            )
            prompt = f"Document this file (`{rel}`):\n\n```\n{content}\n```"

            try:
                doc = self.llm_provider.generate_text(
                    prompt=prompt,
                    system=system,
                    temperature=0.3,
                    max_tokens=512,
                )
                lines.append(doc)
            except Exception:
                lines.append(f"## `{rel}`\n\n_Documentation unavailable._\n")

            lines.append("")

        return "\n".join(lines)

    # ─────────────────────────────────────────────
    # Unified entry point
    # ─────────────────────────────────────────────

    def generate_all(
        self,
        project_name: str = "Project",
        doc_type: str = "all",
    ) -> Dict[str, Path]:
        """
        Write documentation files to the project directory.

        Args:
            project_name: Name shown in doc headers
            doc_type: "contributing" | "changelog" | "api" | "all"

        Returns:
            Dict of {doc_type: Path} for files written
        """
        written: Dict[str, Path] = {}

        if doc_type in ("contributing", "all"):
            path = self.project_dir / "CONTRIBUTING.md"
            path.write_text(self.generate_contributing_guide(project_name))
            written["contributing"] = path

        if doc_type in ("changelog", "all"):
            path = self.project_dir / "CHANGELOG.md"
            path.write_text(self.generate_changelog(project_name))
            written["changelog"] = path

        if doc_type in ("api", "all"):
            path = self.project_dir / "API_DOCS.md"
            path.write_text(self.generate_api_docs())
            written["api"] = path

        return written
