"""
Mock LLM provider for testing without API keys.

Generates realistic test content without requiring actual API calls.
"""

from typing import Optional, Dict, Any
import json


class MockLLMProvider:
    """Mock LLM provider for testing and demos."""

    def __init__(self):
        """Initialize mock provider."""
        self.provider = "mock"
        self.model = "mock-test"
        self.call_count = 0

    def generate_text(
        self,
        prompt: str,
        system: Optional[str] = None,
        temperature: float = 0.7,
        max_tokens: int = 4096,
        json_mode: bool = False,
    ) -> str:
        """Generate mock text."""
        self.call_count += 1

        # Check Phase 4 prompts first (before file-type checks, since diffs may contain filenames)
        if prompt.startswith("Write a commit message for this diff:"):
            return self._mock_commit_message()
        elif "github actions" in prompt.lower() or "workflow" in prompt.lower():
            return self._mock_github_workflow()

        # If json_mode and plan requested, return plan JSON as string
        elif json_mode and "plan" in prompt.lower():
            return json.dumps(self._mock_plan_json())

        # Return appropriate content based on file type
        elif "package.json" in prompt:
            return self._mock_package_json()
        elif "tsconfig.json" in prompt:
            return self._mock_tsconfig()
        elif "main.tsx" in prompt or "main.ts" in prompt or "index.tsx" in prompt:
            return self._mock_main_file()
        elif "App.tsx" in prompt or "App.ts" in prompt:
            return self._mock_app_file()
        elif "README" in prompt:
            return self._mock_readme()
        elif ".gitignore" in prompt:
            return self._mock_gitignore()
        elif "vite.config" in prompt:
            return self._mock_vite_config()
        elif ".env" in prompt:
            return self._mock_env()
        else:
            return self._mock_generic_file()

    def generate_json(
        self,
        prompt: str,
        system: Optional[str] = None,
        temperature: float = 0.3,
        max_tokens: int = 4096,
    ) -> Dict[str, Any]:
        """Generate mock JSON."""
        if "plan" in prompt.lower():
            return self._mock_plan_json()
        return {"success": True, "data": []}

    def test_connection(self) -> bool:
        """Mock connection test."""
        return True

    @staticmethod
    def _mock_package_json() -> str:
        return """{
  "name": "my-project",
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "@vitejs/plugin-react": "^4.0.0",
    "typescript": "^5.0.0",
    "vite": "^4.4.0"
  }
}"""

    @staticmethod
    def _mock_tsconfig() -> str:
        return """{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}"""

    @staticmethod
    def _mock_main_file() -> str:
        return """import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)"""

    @staticmethod
    def _mock_app_file() -> str:
        return """import { useState } from 'react'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <h1>AnywhereCode Generated App</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          This app was generated by AnywhereCode
        </p>
      </div>
    </>
  )
}

export default App"""

    @staticmethod
    def _mock_readme() -> str:
        return """# My Project

This project was generated by AnywhereCode.

## Getting Started

### Prerequisites

- Node.js 18+
- npm or yarn

### Installation

```bash
npm install
```

### Development

```bash
npm run dev
```

The app will be available at `http://localhost:5173`

### Build

```bash
npm run build
```

## Features

- React with TypeScript
- Vite for fast development
- Modern tooling setup
- Ready to extend

## License

MIT
"""

    @staticmethod
    def _mock_gitignore() -> str:
        return """# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*

# Dependencies
node_modules/
dist/
build/

# Environment
.env
.env.local

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
"""

    @staticmethod
    def _mock_vite_config() -> str:
        return """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    open: true,
  },
})
"""

    @staticmethod
    def _mock_env() -> str:
        return """# Application Configuration
VITE_APP_TITLE=My Awesome App
VITE_API_URL=http://localhost:3000
"""

    @staticmethod
    def _mock_generic_file() -> str:
        return """// Generated by AnywhereCode
// This is a placeholder file

export const config = {
  debug: true,
  version: '0.1.0',
}
"""

    @staticmethod
    def _mock_commit_message() -> str:
        return (
            "feat(ui): add responsive layout and dark mode support\n\n"
            "Implemented CSS grid-based responsive layout and added dark mode toggle "
            "with localStorage persistence."
        )

    @staticmethod
    def _mock_github_workflow() -> str:
        return """name: Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      # TODO: add deploy step (e.g. upload to S3, deploy to Vercel, etc.)
"""

    @staticmethod
    def _mock_plan_json() -> Dict[str, Any]:
        return {
            "project_name": "test-project",
            "template": "web-react-vite",
            "description": "A test project generated by AnywhereCode",
            "tech_stack": ["React", "Vite", "TypeScript"],
            "files": [
                {
                    "path": "package.json",
                    "description": "Project dependencies",
                    "file_type": "config",
                    "dependencies": []
                },
                {
                    "path": "tsconfig.json",
                    "description": "TypeScript configuration",
                    "file_type": "config",
                    "dependencies": []
                },
                {
                    "path": "src/main.tsx",
                    "description": "Application entry point",
                    "file_type": "source",
                    "dependencies": []
                },
                {
                    "path": "src/App.tsx",
                    "description": "Root React component",
                    "file_type": "source",
                    "dependencies": ["src/main.tsx"]
                },
                {
                    "path": "README.md",
                    "description": "Project documentation",
                    "file_type": "doc",
                    "dependencies": []
                }
            ],
            "key_features": [
                "Component-based architecture",
                "Fast HMR with Vite",
                "TypeScript support"
            ],
            "estimated_time": "10 minutes",
            "architecture_notes": "Modern React + Vite setup with TypeScript",
            "next_steps": [
                "npm install",
                "npm run dev",
                "Start editing src/App.tsx"
            ]
        }


if __name__ == "__main__":
    mock = MockLLMProvider()
    print("Mock Package.json:")
    print(mock.generate_text("package.json"))
    print("\n✅ Mock LLM working!")
